[package]
name = "plotters-piet"
version = "0.1.0"
edition = "2021"
authors = ["Pascal Sommer"]
license = "MIT OR Apache-2.0"
description = "A Piet backend for Plotters"
repository = "https://github.com/pascal-so/plotters-piet"
keywords = ["visualization", "plotters", "piet", "plot"]
categories = ["visualization"]
readme = "Readme.md"

[dependencies]
piet-common = {version = ">= 0.3, < 0.6", features = ["png"]}
plotters-backend = "0.3.2"
