[workspace]
members = ["plotters-piet"]

[package]
name = "plotters-druid"
version = "0.3.0"
edition = "2021"
authors = ["Pascal Sommer"]
license = "MIT OR Apache-2.0"
description = "Use Plotters as a Druid Widget"
repository = "https://github.com/Pascal-So/plotters-druid"
keywords = ["visualization", "plotters", "druid", "plot", "widget"]
categories = ["visualization", "gui"]
readme = "Readme.md"

[dependencies]
druid = { git = "https://github.com/linebender/druid.git", rev = "b27ea6a618c32f9ea0e8a56822f9487d23401c0d" }
plotters-piet = {version = "0.3.3", path = "plotters-piet"}
plotters = "^0.3"
